### ISSUE TITLE
delete branches

### ISSUE THREAD

**Issue by cheesebroccoli** [CapitalRobotics/Janxs_Brain_2017-2024#22]
Can you please delete as many branches as possible? we definitely do not need all the ones we have and it's starting to bother me.

**Comment by torinriley** [comment]
What branches are you actively using?

**Comment by cheesebroccoli** [comment]
Just the like 2 I made today

**Comment by torinriley** [comment]
names?

**Comment by cheesebroccoli** [comment]
Just delete your branches that youre not using anymore and ill delete mine
